server:
  # 端口号配置
  port:
    http: 7080
    tcp: 7070
  # 文件临时存储路径
  path: upload/
  # http base认证
  auth:
    enable: true
    username: script
    password: script123
  # 基于源IP请求限流(1分钟内请求10次)
  limit:
    enable: true
    # 时长(单位分钟)
    duration: 1
    # 次数
    count: 10
  # IP白名单(","隔开，例如只放行)
  whitelist: 0.0.0.0/0

logs:
  # 日志等级(-1:Debug, 0:Info, 1:Warn, 2:Error, 3:DPanic, 4:Panic, 5:Fatal, -1<=level<=5)
  level: -1
  # 日志路径
  path: logs
  # 文件最大大小, M
  max-size: 50
  # 备份数
  max-backups: 100
  # 存放时间, 天
  max-age: 30
  # 是否压缩
  compress: false
